### ISSUE TITLE
Requiring the package leads to a babel error

### ISSUE THREAD

**Issue by christopherkade** [thenativeweb/terminal-img#1]
Wanted to use your package as a substitute for [terminal-image](https://github.com/sindresorhus/terminal-image) but ran into an error.

Simply requiring the package gives the following:

> internal/modules/cjs/loader.js:583
    throw err;
    ^

> Error: Cannot find module 'babel-runtime/regenerator'
>    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>    at Module.require (internal/modules/cjs/loader.js:637:17)
>    at require (internal/modules/cjs/helpers.js:20:18)
>    at Object.<anonymous> (/Users/pczenika/randog/node_modules/terminal-img/dist/terminalImg.js:3:20)
>    at Module._compile (internal/modules/cjs/loader.js:689:30)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>    at Module.load (internal/modules/cjs/loader.js:599:32)
>    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by goloroden** [comment]
Thanks for bringing up this issue 😊 

I am very sorry for your inconveniences, but I have (hopefully) fixed the problem and released `1.1.1`. Could you please double-check whether it now works for you, and if so, let me know?
